// Misc
export const UNKNOWN = 'UNKNOWN'

// Message
export const POST_MESSAGE = 'POST_MESSAGE'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE'

// Channel
export const CREATE_CHANNEL = 'CREATE_CHANNEL'
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS'
export const FETCH_CHANNELS = 'FETCH_CHANNELS'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const FETCH_CHANNELS_BEGIN = 'FETCH_CHANNELS_BEGIN'
export const INIT_CHANNELS_DONE = 'INIT_CHANNELS_DONE'
export const ADD_MESSAGES = 'ADD_MESSAGES'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL'
export const CHANGE_NEW_MESSAGE = 'CHANGE_NEW_MESSAGE'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const MARK_MESSAGE_READ = 'MARK_MESSAGE_READ'
export const MARK_MESSAGE_READ_SUCCESS = 'MARK_MESSAGE_READ_SUCCESS'
export const JOIN_CHANNEL = 'JOIN_CHANNEL'
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS'
export const ADD_CHANNEL = 'ADD_CHANNEL'

// Direct Channel
export const FETCH_DIRECT_CHANNELS = 'FETCH_DIRECT_CHANNELS'
export const FETCH_DIRECT_CHANNELS_SUCCESS = 'FETCH_DIRECT_CHANNELS_SUCCESS'
export const INIT_DIRECT_CHANNELS_DONE = 'INIT_DIRECT_CHANNELS_DONE'
export const JOIN_DIRECT_CHANNEL = 'JOIN_DIRECT_CHANNEL'
export const JOIN_DIRECT_CHANNEL_SUCCESS = 'JOIN_DIRECT_CHANNEL_SUCCESS'
export const ADD_DIRECT_CHANNEL = 'ADD_DIRECT_CHANNEL'
export const OPEN_DIRECT_CHANNEL = 'OPEN_DIRECT_CHANNEL'

// User
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const SYNC_USERS_PRESENCES = 'SYNC_USERS_PRESENCES'
export const ADD_USER = 'ADD_USER'

// Fetching
export const FETCHING_FAILURE = 'FETCHING_FAILURE'
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS'

// Auth
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

// Local
export const OPEN_NEW_CHANNEL_MODAL = 'OPEN_NEW_CHANNEL_MODAL'
export const CLOSE_NEW_CHANNEL_MODAL = 'CLOSE_NEW_CHANNEL_MODAL'
export const OPEN_JOIN_CHANNEL_MODAL = 'OPEN_JOIN_CHANNEL_MODAL'
export const CLOSE_JOIN_CHANNEL_MODAL = 'CLOSE_JOIN_CHANNEL_MODAL'
export const OPEN_JOIN_DIRECT_CHANNEL_MODAL = 'OPEN_JOIN_DIRECT_CHANNEL_MODAL'
export const CLOSE_JOIN_DIRECT_CHANNEL_MODAL = 'CLOSE_JOIN_DIRECT_CHANNEL_MODAL'
