// Misc
export const UNKNOWN = 'UNKNOWN'

// Message
export const POST_MESSAGE = 'POST_MESSAGE'
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS'
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE'

// Channel
export const CREATE_CHANNEL = 'CREATE_CHANNEL'
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS'
export const FETCH_CHANNELS = 'FETCH_CHANNELS'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const FETCH_CHANNELS_BEGIN = 'FETCH_CHANNELS_BEGIN'
export const INIT_CHANNELS_DONE = 'INIT_CHANNELS_DONE'
export const ADD_MESSAGES = 'ADD_MESSAGES'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL'
export const CHANGE_NEW_MESSAGE = 'CHANGE_NEW_MESSAGE'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'

// Auth
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

// Local
export const OPEN_NEW_CHANNEL_MODAL = 'OPEN_NEW_CHANNEL_MODAL'
export const CLOSE_NEW_CHANNEL_MODAL = 'CLOSE_NEW_CHANNEL_MODAL'
